---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/mototorcycles":
    parameters:
    - name: user_id
      in: query
      type: integer
      description: user_id
      schema:
        type: object
        properties:
          motors:
            model:
              type: string
            image:
              type: string
            price:
              type: integer
            description:
              type: text
            duration_months:
              type: integer
    get:
      summary: list motorcycles
      responses:
        '200':
          description: successful
    post:
      summary: create motorcycle
      responses:
        '200':
          description: successful
  "/api/motorcycles/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show motorcycle
      responses:
        '200':
          description: successful
    patch:
      summary: update motorcycle
      responses:
        '200':
          description: successful
    put:
      summary: update motorcycles
      responses:
        '200':
          description: successful
    delete:
      summary: delete motorcycle
      responses:
        '200':
          description: successful
  "/api/reservations":
    parameters:
    - name: motor_id
      in: query
      type: integer
      schema:
        type: object
        properties:
          reservations:
            city:
              type: string
            date:
              type: string
    get:
      summary: list reservations
      responses:
        '200':
          description: successful
    post:
      summary: create reservation
      responses:
        '200':
          description: successful
  "/api/reservations/{id}":
    parameters:
    - name: user_id
      in: path
      description: user_id
      required: true
      schema:
        type: string
    get:
      summary: show reservation
      responses:
        '200':
          description: successful
    patch:
      summary: update reservation
      responses:
        '200':
          description: successful
    put:
      summary: update reservation
      responses:
        '200':
          description: successful
    delete:
      summary: delete reservation
      responses:
        '200':
          description: successful
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
